datastore:
  kind: mdp
  config_path: era3h.datastore.yaml 
training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      z850.0hPa: 0.5
      t850.0hPa: 0.5
      u850.0hPa: 0.5
      v850.0hPa: 0.5
      wind_speed850.0hPa: 1.0

