datastore:
  kind: mdp
  config_path: era_med.datastore.yaml 
training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      z850.0hPa: 1.0
      r850.0hPa: 1.0
      t850.0hPa: 1.0
      # u850.0hPa: 1.0
      # v850.0hPa: 1.0
      wind_speed850.0hPa: 1.0

